= Configure MiniKube for Local testing of Spring Cloud Dataflow

In order to ensure to manage the specific versions of data flow and skipper containers you can set SKIPPER_VERSION and DATAFLOW_VERSION environmental variable and then invoke `./src/local/pull-dataflow.sh` and `./src/local/pull-skipper.sh`

If you want to use a locally built image you can invoke
`./src/loca/build-skipper-image.sh` or `./src/local/build-dataflow.sh`

Configure and start minikube and deploy the helm chart for Spring Cloud Dataflow.

You can change the type of driver used by setting `K8S_DRIVER` to one of `tmc, kvm2, docker, vmware, virtualbox, podman, vmwarefusion`, the default is 'kind'

== Create Configure k8s environment
=== TMC Cluster in Cloud

When using TMC Cluster configure TMC_CLUSTER environmental variable with cluster name:

[source,shell]
....
export TMC_CLUSTER=<cluster name>
source ./src/local/tmc/set-cluster.sh
....

=== Local Cluster

When using a local kind or minikube cluster:

[source,shell]
....
./src/local/configure-k8s.sh
....

and follow instruction to update `src/local/k8s/metallb-configmap.yaml`


Configure and deploy the Spring Cloud Data Flow containers.

[source,shell]
....
./src/local/launch-scdf.sh
....

Delete the deployment.

[source,shell]
....
./src/local/k8s/delete-scdf.sh
....

Delete the cluster

[source,shell]
....
./src/local/destroy-k8s.sh
....
