apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
    component: kafka-broker
  name: kafka-broker
spec:
  ports:
    - name: kafka-port
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka
    component: kafka-broker
  type: LoadBalancer
