apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-zk
    component: kafka-zk
  name: kafka-zk
spec:
  ports:
    - name: kafka-zk-port
      port: 2181
      protocol: TCP
      targetPort: 2181
  selector:
    app: kafka-zk
    component: kafka-zk
  type: LoadBalancer
