#!/bin/bash


function generate_manifest() {
cat << EOF > ./scdf-manifest.yml

applications:
- name: scdf-server
  path: ./scdf-server.jar
  memory: 1G
  host: dataflow-server-\${random-word}
  services:
    - mysql
    - redis
  env:
    EXTERNAL_SERVERS_REQUIRED: true
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_URL: $SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_URL
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_DOMAIN: $SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_DOMAIN
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_ORG: $SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_ORG
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SPACE: $SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SPACE
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_USERNAME: $SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_USERNAME
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_PASSWORD: $SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_PASSWORD
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SKIP_SSL_VALIDATION: $SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SKIP_SSL_VALIDATION
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_SERVICES: rabbit
    MAVEN_REMOTE_REPOSITORIES_REPO1_URL: $MAVEN_REMOTE_REPOSITORIES_REPO1_URL
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_API_TIMEOUT: $SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_API_TIMEOUT

EOF

}

function push_application() {
  cf push -f scdf-manifest.yml
  SERVER_URI=$(cf app scdf-server | grep urls | awk '{print $2}' | sed 's:,::g')
  $SERVER_URI="http://$SERVER_URI"
  echo "SCDF SERVER URI: $SERVER_URI"
  export $SERVER_URI
}


download $PWD
generate_manifest
push_application
