name: SCDF AT Rabbit (Shepherd)

on:
  workflow_dispatch:
    inputs:
      cf-host:
        type: string
        description: 'CF host name (e.g. "z9bdf097a")'
        required: true
      cf-api-url:
        type: string
        description: 'CF api url ("https://api.sys.tas.z9bdf097a.shepherd.lease"")'
        required: true
      cf-apps-domain:
        type: string
        description: 'CF apps domain ("apps.tas.z9bdf097a.shepherd.lease")'
        required: true
      tests:
        type: string
        description: 'Test classes'
        default: ''
  workflow_call:
    inputs:
      cf-host:
        type: string
        description: 'CF host name (e.g. "z9bdf097a")'
        required: true
      cf-api-url:
        type: string
        description: 'CF api url ("https://api.sys.tas.z9bdf097a.shepherd.lease"")'
        required: true
      cf-apps-domain:
        type: string
        description: 'CF apps domain ("apps.tas.z9bdf097a.shepherd.lease")'
        required: true
      tests:
        type: string
        description: 'Test classes'
        default: ''
    secrets:
      CF_PASSWORD:
        required: true

jobs:
  acceptance-tests-rabbit:
    uses: ./.github/workflows/at-common-workflow.yml
    with:
      cf-host: ${{ inputs.cf-host }}
      cf-api-url: ${{ inputs.cf-api-url }}
      cf-apps-domain: ${{ inputs.cf-apps-domain }}
      binder: rabbit
      tests: ${{ inputs.tests }}
    secrets:
      CF_USERNAME: 'admin'
      CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
