name: SCDF AT Kafka (Shepherd)

on:
  workflow_dispatch:
    inputs:
      tests:
        type: string
        default: ''
        description: 'Test classes'
      cf-host:
        type: string
        description: 'CF host name (e.g. "bucharest")'
        required: true
  workflow_call:
    inputs:
      cf-host:
        type: string
        description: 'CF host name (e.g. "bucharest")'
        required: true
    secrets:
      CF_ADMIN_PASSWORD:
        required: true
      KAFKA_USERNAME:
        required: true
      KAFKA_PASSWORD:
        required: true
      KAFKA_BROKER_ADDRESS:
        required: true

jobs:
  kafka-2:
    uses: ./.github/workflows/at-common-workflow.yml
    with:
      cf_host: ${{ inputs.cf-host }}
      cf_index: 2
      binder: kafka
      tests: ${{ inputs.tests }}
    secrets:
      CF_USERNAME: 'admin'
      CF_ENV_0_PASSWORD: 'not-used'
      CF_ENV_1_PASSWORD: 'not-used'
      CF_ENV_2_PASSWORD: ${{ secrets.CF_ADMIN_PASSWORD }}
      KAFKA_USERNAME: ${{ secrets.KAFKA_USERNAME }}
      KAFKA_PASSWORD: ${{ secrets.KAFKA_PASSWORD }}
      KAFKA_BROKER_ADDRESS: ${{ secrets.KAFKA_BROKER_ADDRESS }}
