name: SCDF AT Rabbit - env 1

on:
  workflow_dispatch:

jobs:
  rabbit-1:
    uses: ./.github/workflows/at-common-workflow.yml
    with:
      cf_host: needles
      cf_index: 1
      binder: rabbit
    secrets:
      CF_USERNAME: ${{secrets.CF_USERNAME}}
      CF_ENV_0_PASSWORD: ${{secrets.CF_ENV_0_PASSWORD}}
      CF_ENV_1_PASSWORD: ${{secrets.CF_ENV_1_PASSWORD}}
      SQL_USERNAME: ${{secrets.SQL_USERNAME}}
      SQL_PASSWORD: ${{secrets.SQL_PASSWORD}}
      SQL_SYSTEM_USERNAME: ${{secrets.SQL_USERNAME}}
      SQL_SYSTEM_PASSWORD: ${{secrets.SQL_PASSWORD}}
      SQL_HOST: ${{secrets.SQL_HOST}}
      SQL_PORT: ${{secrets.SQL_PORT}}
